export const ROUTES = {
  LANDING: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  ADMIN_USERS: "/admin/users",
  ADMIN_COMPANIES: "/admin/companies",
  ADMIN_COMPANY_USERS: "/admin/companies/:companyId/users",
  ADMIN_CATALOGS: "/admin/catalogs",
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_CABINETS: "/admin/cabinets",
  CATALOGS: "/catalogs",
  CATALOG_CATEGORIES: "/catalogs/:id/categories",
  CATEGORY_CABINETS: "/categories/:id/cabinets",
  WORKSPACES: "/workspaces",
  WORKSPACE_EDITOR: "/workspaces/:id",
  TEAM: "/team",
  INVITATIONS: "/invitations",
} as const;